[package]
name = "packet_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
pnet = "0.31.0"
pnet_datalink = "0.31.0"
pnet_packet = "0.31.0"
ipnetwork = "0.20.0"
clap = { version = "4.1.8", features = ["derive"] }
